# Generated by Django 4.2.2 on 2023-07-01 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 1, 16, 20, 10, 219370, tzinfo=datetime.timezone.utc)),
        ),
    ]
